version: "2.4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    cpus: "0.75"
    mem_limit: 1440m
    env_file:
      - .env
